stocks = [
    'RELIANCE.NS', 
    'TCS.NS', 
    'HDFCBANK.NS', 
    'ICICIBANK.NS',
    'INFY.NS', 
    'SBIN.NS', 
    'KOTAKBANK.NS',
    'BAJFINANCE.NS',
    'BHARTIARTL.NS', 
    'LT.NS', 
    'AXISBANK.NS', 
    'MARUTI.NS', 
    'INDUSINDBK.NS', 
    'ITC.NS',
    'ASIANPAINT.NS', 
    'ONGC.NS', 
    'TATAMOTORS.NS', 
    'POWERGRID.NS', 
    'NTPC.NS', 
    'ULTRACEMCO.NS',
    'WIPRO.NS', 
    'COALINDIA.NS', 
    'IOC.NS', 
    'HCLTECH.NS', 
    'SUNPHARMA.NS', 
    'JSWSTEEL.NS',
    'NESTLEIND.NS', 
    'TECHM.NS', 
    'DRREDDY.NS', 
    'BAJAJFINSV.NS',
    'ADANIPORTS.NS'
]

market_index = '^BSESN'